name: Daily Update CSV

on:
  schedule:
    - cron: "55 15 * * *"
  # workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: update csv
        run: |
          python daily_deal.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update csv
