name: Daily Update CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "55 15 * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: update csv
        run: |
          python daily_deal.py \
              && git config user.email "$GITHUB_ACTOR@users.noreply.github.com" \
              && git config --global user.name "$GITHUB_ACTOR" \
              && git commit 'update csv file' daily-house-deal.csv \
              && git push origin master
